// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import CharactersController from "./characters_controller"
// application.register("characters", CharactersController)

import DescriptionChangeController from "./description_change_controller"
application.register("description-change", DescriptionChangeController)

import CampaignDescriptionChangeController from "./campaign_description_change_controller"
application.register("campaign-description-change", CampaignDescriptionChangeController)

import ImagesHomeController from "./images_home_controller"
application.register("images-home", ImagesHomeController)

import DiceRollerController from "./dice_roller_controller"
application.register("dice-roller", DiceRollerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)
