// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DescriptionChangeController from "./description_change_controller"
application.register("description-change", DescriptionChangeController)

import CampaignDescriptionChangeController from "./campaign_description_change_controller"
application.register("campaign-description-change", CampaignDescriptionChangeController)

import DiceRollerController from "./dice_roller_controller"
application.register("dice-roller", DiceRollerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
